name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Infrastructure/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Infrastructure/**'
      - 'docs/**'
      - '*.md'
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ToppingsApi/Dockerfile --tag toppings-api:$(date +%s)
      working-directory: ToppingsApi
    - name: Build the Helm Chart
      run: 
