name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Infrastructure/**'
  workflow_dispatch:
  
jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: terraform init

    - id: plan
      run: terraform plan -no-color